version: "3.4"

services:

  mysql:
    image: mysql
    environment:
      MYSQL_USER: arboruser
      MYSQL_PASSWORD: arborpassword
      MYSQL_DATABASE: arbordbnew
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
      